### ISSUE TITLE
Accés al diccionari de sentiments

### ISSUE THREAD

**Issue by xfim** [pbalaguer19/catalan-sentiment-analysis#1]
Benvolgut @pbalaguer19 ,
He arribat a aquest repositori cercant alguna mena de diccionari de classificació de paraules i sentiments en català. Veig que a l'arxiu
[/src/data/senticon.ca.xml](/src/data/senticon.ca.xml) hi ha quelcom que m'aniria molt bé.
Veig  també que el repositori forma part del treball final de grau, però no veig enlloc quina llicència té l'arxiu i si jo en podria fer ús (per finalitats no comercials).

L'has generat tu, l'arxiu senticon.ca.xml? Si és així, et faria res, doncs, que el fes servir l'arxiu, i si en surt una publicació t'ha agraís? Si no, on el puc trobar, l'autor original i com citar-ho?

Gràcies i salutacions,

**Comment by pbalaguer19** [comment]
Hola @xfim .
Efectivament aquest projecte va ser el meu treball final de grau i des de llavors que no l'he tocat més. Si en vols més informació, vam publicar un article anomenat "CatSent: a Catalan sentiment analysis website" (diria que per internet es pot trobar). Allà explica que justament aquesta classificació de sentiments està extreta d'un projecte públic anomenat "MLSentiCon".
Per part meva no tinc cap problema en que l'utilitzis!! Endavant ;)

**Comment by xfim** [comment]
Gràcies @pbalaguer19 .

He vist també el vostre article, però en aquest cas era en aquest repositori on m'ha semblat trobar-hi més detalls. Ara no sé pas trobar aquest projecte. Però si no hi tens cap problema, doncs tiro endavant.

Moltes gràcies.
